### ISSUE TITLE
Latest Zlog won't compile with gcc 4.7.2

### ISSUE THREAD

**Issue by tleonhardt** [HardySimpson/zlog#12]
I downloaded the latest zlog tonight (2012-Nov-15) and tried compiling it with gcc 4.7.2 and it went like shown below:

todd@todd-Desk ~/Downloads/zlog-master $ make
cd src && make all
make[1]: Entering directory `/home/todd/Downloads/zlog-master/src'
cc -std=c99 -pedantic -c -O2 -fPIC  -Wall -Werror -Wstrict-prototypes -g -ggdb buf.c
In file included from /usr/include/string.h:642:0,
                 from zc_xplatform.h:41,
                 from zc_defs.h:26,
                 from buf.c:26:
In function ‘memset’,
    inlined from ‘zlog_buf_adjust_append’ at buf.c:615:11:
/usr/include/x86_64-linux-gnu/bits/string3.h:82:30: error: call to ‘__warn_memset_zero_len’ declared with attribute warning: memset used with constant zero length parameter; this could be due to transposed parameters [-Werror]
cc1: all warnings being treated as errors
make[1]: *** [buf.o] Error 1
make[1]: Leaving directory`/home/todd/Downloads/zlog-master/src'
make: **\* [all] Error 2

The same exact code compiles fine on another computer with gcc 4.6.3

P.S.  I've been using zlog for a few months and love how it is lightweight with a simple API and flexible rules, formats, etc.
